#helm:generate helm template -o $HELM_GENERATE_DIR/manifests/deis-registry-rc.yaml -d $HELM_GENERATE_DIR/tpl/objectstorage.toml $HELM_GENERATE_DIR/tpl/deis-registry-rc.yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: deis-registry
  namespace: deis
  labels:
    heritage: deis
spec:
  replicas: 1
  selector:
    app: deis-registry
  template:
    metadata:
      labels:
        app: deis-registry
    spec:
      serviceAccount: deis-registry
      containers:
        - name: deis-registry
          image: quay.io/deisci/registry:canary
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /v2/
              port: 5000
            initialDelaySeconds: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /v2/
              port: 5000
            initialDelaySeconds: 1
            timeoutSeconds: 1
          env:
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
            - name: REGISTRY_LOG_LEVEL
              value: info
            - name: REGISTRY_STORAGE
              value: {{default "minio" .storage}}
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: registry-storage
              mountPath: /var/lib/registry
            - name: registry-creds
              mountPath: /var/run/secrets/deis/registry/creds
      volumes:
        - name: registry-storage
          emptyDir: {}
        - name: registry-creds
          secret:
            secretName: objectstorage-keyfile
