apiVersion: v1
kind: Pod
metadata:
  name: workflow-dev-e2e
  namespace: deis
  labels:
    heritage: deis
spec:
  restartPolicy: Never
  containers:
  - name: tests
    image: quay.io/deisci/workflow-e2e:git-0b0156d
    imagePullPolicy: Always
    env:
      - name: GINKGO_NODES
        value: "15"
      - name: JUNIT
        value: "true"
    volumeMounts:
    - name: artifact-volume
      mountPath: /root
  - name: artifacts
    image: busybox
    imagePullPolicy: Always
    command: ["tail", "-f", "/dev/null"]
    volumeMounts:
    - name: artifact-volume
      mountPath: /root
  volumes:
  - name: artifact-volume
    emptyDir: {}
